config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'dishes#home'
  resources :dishes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dishes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :set_user

  private
  def set_user
  	@user_email = current_user.email if current_user.present?
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_dish


	def index
		@dishes = Dish.all.includes(:user)
	end

	def home
		@dish_types = ["Italian","Thailand","Indian"]
		@dish_types = [params[:search]] if @dish_types.include?(params[:search])
	end

	def new

	end

	def create
		@dish = Dish.create(dish_params)
		@dish.user_id = params[:user_id]
		@dish.save
		UserMailer.info_email(@user_email,"created").deliver!
		redirect_to dishes_path
		flash[:notice] ="Dish has been created successfully"
		
	end

	def destroy
		@dish.destroy
		UserMailer.info_email(@user_email, "deleted").deliver!
		redirect_to dishes_path
		flash[:notice] ="Dish has been deleted successfully"
	end

	private

	def set_dish
    	@dish = params[:id].blank? ? Dish.new : Dish.find_by_id(params[:id])  
	end

	def dish_params
		params.require(:dish).permit(:user_id,:dish_type,:recipe_type,:user_group)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/home.html.erb
<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-3">

	<%= form_tag root_path, method: :get, class: "navbar-form navbar-left", role: "search" do %>
		<p>
			<span class="form-feild">
				<%= text_field_tag :search,  nil, placeholder: "Search", class: "form-control" %>
			</span>
			<%#= text_field_tag :search,  nil, placeholder: "Search", class: "form-control" %>
			<%= submit_tag "Search", name: nil, class: "btn btn-default" %>
		</p>
	<%end%>	
	<table class="table mmt-table" id="emp_table">
		<thead>							
			<tr>
				<th>Dish Type</th>
				<th>Actions</th> 
			</tr>	
		</thead>
		<tbody>
			<% @dish_types.each do |dish| %>
			<tr>
			
 				<td class="account_name"><%= dish %></td>
				
				<td class="actions">
					<a href="<%= new_dish_path(dish_type: dish) %>" class="view" data-toggle="tooltip" data-placement="bottom" title="New Dish"><img src="/assets/list_user.png" /></a>
				  </td>
				</tr>
			<% end %>						
		</tbody>
	</table>
</div>

app/views/dishes/index.html.erb
<table class="table mmt-table" id="emp_table">
		<thead>							
			<tr>
				<th>User Email</th>
				<th>Dish Type</th>
				<th>Recipe Type</th>
				<th>User Group</th>
				<th>Action</th>
			</tr>	
		</thead>
		<tbody>
			<% @dishes.each do |dish| %>
			<tr>
			
 				<td><%= dish.user.email %></td>
 				<td><%= dish.dish_type %></td>
 				<td><%= dish.recipe_type %></td>
 				<td><%= dish.user_group %></td>
 				<td><%= link_to 'Destroy', dish_path(dish),
            data: {:confirm => 'Are you sure?'}, :method => :delete %></td>
				</tr>
			<% end %>						
		</tbody>
	</table>

app/views/dishes/new.html.erb
<div class="row">
	<div class="col-lg-5 col-md-6 col-sm-7 col-xs-12">
	<%= form_for @dish do |f| %>
		  <div class="form-group">
		  	<label for="record_type">User Group</label>
		  	<%= f.select :user_group, [["0-10"], ["10-60"], ["60+"]], {}, {class: 'select-controller'}%>
		  </div>
		  <div class="form-group">
		  	<label for="record_type">Dish Type</label>
		  	<%= f.select :dish_type, [["Italian"], ["Thailand"], ["Indian"]], {selected: params[:dish_type]}, {class: 'select-controller'}%>
		  </div>
		  <div class="form-group">
		  	<label for="record_type">Recipe Type</label>
		  	<%= f.select :recipe_type, [["Spicy"], ["Normal"], ["Tadka"]], {}, {class: 'select-controller'}%>
		  </div>
		  <%= hidden_field_tag :user_id, current_user.id %>

		  <div class="form-group mmt-credentials-btn-sec">
		  	<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<%= submit_tag "Submit", class: "btn mmt-credentials-btn mr10 mb10" %>
		  		</div>
		  	</div>
		  </div>
		<%end%>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>RecipeApp</title>
		<%= csrf_meta_tags %>

			<!-- Latest compiled and minified CSS -->
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" >
			<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js">
			<!-- Optional theme -->
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
			<%= javascript_include_tag "application", "data-turbolinks-track" => true %>


			<!-- Latest compiled and minified JavaScript -->
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

	</head>

		<body>
			
			<div class="container">
				<nav class="navbar navbar-default "> <!-- navbar-fixed-top-->
					<div class="container-fluid"> 
						<div class="navbar-header">
							<button type="button" class="collapsed navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6" aria-expanded="false"> 
								<span class="sr-only">Toggle navigation</span> 
								<span class="icon-bar"></span> 
								<span class="icon-bar"></span> 
								<span class="icon-bar"></span> 
							</button> 

							<a class="navbar-brand" > </a>
							<%= link_to root_path do %>
								<button type="button" class="btn btn-default navbar-btn">Home</button> 
							<%end%>

							<%= link_to dishes_path do%>
								<button type="button" class="btn btn-default navbar-btn">Dish List</button>
							<%end%> 
							<%= link_to new_dish_path do%>
								<button type="button" class="btn btn-default navbar-btn">New Dish</button>
							<%end%> 

						</div> 

						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-3">
							<% if user_signed_in? %>
								<%= link_to destroy_user_session_path, :method => :delete do %> 
								<button type="button" class="btn btn-default navbar-btn">Sign out</button>
								<%end%>
									<div class="navbar-center navbar-brand">Signed in as <strong>
										<%= current_user.email %>.</strong>
									</div>
								<% else %>

								<%= link_to new_user_session_path do %>
									<button type="button" class="btn btn-default navbar-btn">Sign in</button>
								<%end%>
								<%= link_to new_user_registration_path do %>
									<button type="button" class="btn btn-default navbar-btn"> Sign up</button>
								<%end%>
							<%end%> 
						</div>


						<div class="footer navbar-fixed-bottom">
							<h4 style="text-align:right;">
								<span style="color: #cc00ff;">
							Sample Dish Application</h4></span>
						</div>

						<% flash.each do |name, msg| %>
							<%= content_tag(:div, msg, class: "alert") %>
						<% end%>

					</nav>

				</div>

			<%= yield %>
		</body>
</html>